import { useDeferredValue, useState } from 'react';
import type { FormEvent } from 'react';
import { File as FileIcon, FileText, Image as ImageIcon, Link as LinkIcon, Music, Video } from 'lucide-react';
import { useLocation, useNavigate, useSearchParams } from 'react-router-dom';
import { UploadTray } from '../components/uploads/UploadTray';
import { Button } from '../components/ui/Button';
import { Card } from '../components/ui/Card';
import { ViewToolbar } from '../components/ui/ViewToolbar';
import { type Note, type NoteInput, useNoteActions } from '../data/useNotes';
import { useOrganization } from '../data/useOrganization';
import { useProjects } from '../data/useProjects';
import { type ResourceDetail, type ResourceSummary, useLinkActions, useResource, useResourceAccess, useResourceActions, useResources } from '../data/useResources';

export function Library() {
  const [viewMode, setViewMode] = useState<'grid' | 'list'>('list'); const [creating, setCreating] = useState<'choose' | 'note' | 'link' | null>(null); const navigate = useNavigate(); const location = useLocation(); const resourceId = location.pathname.match(/^\/library\/([^/]+)$/)?.[1];
  const [searchParams, setSearchParams] = useSearchParams(); const query = searchParams.get('q') ?? ''; const deferredQuery = useDeferredValue(query); const type = searchParams.get('type') as 'note' | 'file' | 'link' | null; const projectId = searchParams.get('projectId') ?? ''; const folderId = searchParams.get('folderId') ?? '';
  const resources = useResources({ query: deferredQuery || undefined, type: type ?? undefined, projectId: projectId || undefined, folderId: folderId || undefined }); const detail = useResource(resourceId); const noteActions = useNoteActions(); const linkActions = useLinkActions(); const projects = useProjects('active'); const organization = useOrganization(projectId || undefined); const items = resources.data?.pages.flatMap(page => page.data) ?? []; const projectItems = projects.data?.pages.flatMap(page => page.data) ?? []; const activeFilters = Boolean(query || type || projectId || folderId);
  const setFilter = (name: string, value?: string) => { const next = new URLSearchParams(searchParams); if (value) next.set(name, value); else next.delete(name); if (name === 'projectId') next.delete('folderId'); setSearchParams(next, { replace: true }); };
  const listDestination = `/library${searchParams.size ? `?${searchParams}` : ''}`;
  if (resourceId) { const selected = detail.data; return <main className="w-full px-6 md:px-8 py-6"><Button onClick={() => navigate(listDestination)}>← Biblioteca</Button>{detail.isPending && <p role="status" className="mt-5">Cargando recurso…</p>}{detail.isError && <p role="alert" className="mt-5 text-red-600">No se pudo abrir el recurso.</p>}{selected?.type === 'note' && <NoteEditor note={{ ...selected, currentVersion: { id: '', ordinal: 1, content: selected.content ?? '' } }} busy={noteActions.update.isPending} onCancel={() => navigate(listDestination)} onSave={async body => { const saved = await noteActions.update.mutateAsync({ id: selected.id, body }); return saved.contentUnchanged; }}/>} {selected?.type === 'file' && <FileResource resource={selected}/>} {selected?.type === 'link' && <LinkResource resource={selected}/>}</main>; }
  return <main className="w-full px-6 md:px-8 py-6 pb-32" aria-labelledby="library-title">
    <div className="flex items-center justify-between"><div><h1 id="library-title" className="text-xl font-semibold">Biblioteca</h1><p className="text-sm text-outline">Recursos reutilizables en distintos proyectos y diagramas.</p></div><ViewToolbar viewMode={viewMode} setViewMode={setViewMode} onNew={() => setCreating('choose')}/></div>
    <section className="mt-5 rounded-lg border border-border p-3" aria-label="Buscar y filtrar recursos"><div className="grid gap-3 md:grid-cols-4"><label className="text-sm font-medium">Buscar<input className="mt-1 w-full rounded border border-border bg-background p-2" type="search" value={query} placeholder="Nombre del recurso" onChange={event => setFilter('q', event.target.value)}/></label><label className="text-sm font-medium">Tipo<select className="mt-1 w-full rounded border border-border bg-background p-2" value={type ?? ''} onChange={event => setFilter('type', event.target.value)}><option value="">Todos</option><option value="note">Notas</option><option value="file">Archivos</option><option value="link">Enlaces</option></select></label><label className="text-sm font-medium">Proyecto<select className="mt-1 w-full rounded border border-border bg-background p-2" value={projectId} onChange={event => setFilter('projectId', event.target.value)}><option value="">Todos</option>{projectItems.map(project => <option key={project.id} value={project.id}>{project.name}</option>)}</select></label><label className="text-sm font-medium">Carpeta<select className="mt-1 w-full rounded border border-border bg-background p-2" value={folderId} disabled={!projectId || organization.isPending} onChange={event => setFilter('folderId', event.target.value)}><option value="">Todas</option>{organization.data?.folders.filter(folder => !folder.archivedAt).map(folder => <option key={folder.id} value={folder.id}>{folder.name}</option>)}</select></label></div>{projects.hasNextPage && <Button className="mt-2" variant="outline" disabled={projects.isFetchingNextPage} onClick={() => projects.fetchNextPage()}>Cargar más proyectos</Button>}{activeFilters && <div className="mt-3 flex flex-wrap items-center gap-2" aria-label="Filtros activos"><span className="text-xs text-outline">Filtros activos:</span>{query && <Button variant="outline" onClick={() => setFilter('q')}>Búsqueda: {query} ×</Button>}{type && <Button variant="outline" onClick={() => setFilter('type')}>Tipo: {type} ×</Button>}{projectId && <Button variant="outline" onClick={() => setFilter('projectId')}>Proyecto ×</Button>}{folderId && <Button variant="outline" onClick={() => setFilter('folderId')}>Carpeta ×</Button>}<Button onClick={() => setSearchParams({}, { replace: true })}>Limpiar todo</Button></div>}</section>
    <UploadTray/>
    {resources.isPending && <p role="status" className="mt-6">Cargando Biblioteca…</p>}
    {resources.isFetching && !resources.isPending && <p className="mt-3 text-sm text-outline">Actualizando resultados…</p>}
    {resources.isError && <div role="alert" className="mt-6"><p className="text-red-600">No se pudo cargar la Biblioteca.</p><Button variant="outline" onClick={() => resources.refetch()}>Reintentar</Button></div>}
    {!resources.isPending && !resources.isError && items.length === 0 && (activeFilters ? <section className="mt-8 rounded-lg border border-dashed border-border p-10 text-center"><h2 className="font-medium">No hay resultados</h2><p className="mt-1 text-sm text-outline">Prueba retirando uno o más filtros.</p><Button className="mt-4" variant="outline" onClick={() => setSearchParams({}, { replace: true })}>Limpiar filtros</Button></section> : <section className="mt-8 rounded-lg border border-dashed border-border p-10 text-center"><FileText className="mx-auto text-outline" size={36}/><h2 className="mt-3 font-medium">Tu Biblioteca está vacía</h2><p className="mt-1 text-sm text-outline">Crea una nota, guarda un enlace o carga un archivo.</p><Button className="mt-4" variant="primary" onClick={() => setCreating('choose')}>Crear recurso</Button></section>)}
    {!resources.isPending && !resources.isError && <p className="mt-4 text-sm text-outline" aria-live="polite">{items.length}{resources.hasNextPage ? '+' : ''} {items.length === 1 ? 'resultado' : 'resultados'}</p>}
    {items.length > 0 && (viewMode === 'grid' ? <div className="mt-6 grid grid-cols-1 sm:grid-cols-3 md:grid-cols-4 gap-4">{items.map(resource => <Card key={resource.id} title={resource.title} subtitle={resource.description || resource.mediaType || 'Nota'} icon={<ResourceIcon resource={resource} size={32}/>} onClick={() => navigate(`/library/${resource.id}${searchParams.size ? `?${searchParams}` : ''}`)}/>)}</div> : <div className="mt-6 divide-y divide-border border-y border-border">{items.map(resource => <button key={resource.id} className="flex w-full items-center gap-3 py-3 text-left hover:bg-surface-variant focus-visible:outline-2" onClick={() => navigate(`/library/${resource.id}${searchParams.size ? `?${searchParams}` : ''}`)}><ResourceIcon resource={resource} size={18}/><span className="flex-1"><strong className="block font-medium">{resource.title}</strong><small className="text-outline">{resource.description || resource.mediaType || 'Nota'} · {resource.status}</small></span><time className="text-xs text-outline">{new Date(resource.updatedAt).toLocaleDateString()}</time></button>)}</div>)}
    {resources.hasNextPage && <Button className="mt-5" variant="outline" onClick={() => resources.fetchNextPage()}>Cargar más</Button>}
    {creating && <div className="fixed inset-0 z-50 overflow-auto bg-background p-6">{creating === 'choose' && <section className="mx-auto mt-16 max-w-md"><h2 className="text-xl font-semibold">Crear recurso</h2><div className="mt-5 grid gap-3"><Button variant="primary" onClick={() => setCreating('note')}>Crear nota</Button><Button variant="outline" onClick={() => setCreating('link')}>Guardar enlace web</Button><Button onClick={() => setCreating(null)}>Cancelar</Button></div></section>}{creating === 'note' && <NoteEditor busy={noteActions.create.isPending} onCancel={() => setCreating(null)} onSave={async body => { const saved = await noteActions.create.mutateAsync(body); setCreating(null); navigate(`/library/${saved.id}${searchParams.size ? `?${searchParams}` : ''}`); return false; }}/>} {creating === 'link' && <LinkEditor busy={linkActions.create.isPending} onCancel={() => setCreating(null)} onSave={async url => { const saved = await linkActions.create.mutateAsync({ url }); setCreating(null); navigate(`/library/${saved.id}${searchParams.size ? `?${searchParams}` : ''}`); }}/>}</div>}
  </main>;
}

function ResourceIcon({ resource, size }: { resource: ResourceSummary; size: number }) { if (resource.type === 'note') return <FileText size={size}/>; if (resource.type === 'link') return <LinkIcon size={size}/>; if (resource.mediaType?.startsWith('image/')) return <ImageIcon size={size}/>; if (resource.mediaType?.startsWith('audio/')) return <Music size={size}/>; if (resource.mediaType?.startsWith('video/')) return <Video size={size}/>; return <FileIcon size={size}/>; }

function FileResource({ resource }: { resource: ResourceDetail }) {
  const previewable = resource.mediaType === 'application/pdf' || resource.mediaType?.startsWith('image/'); const media = resource.mediaType?.startsWith('audio/') || resource.mediaType?.startsWith('video/'); const preview = useResourceAccess(resource.id, Boolean(previewable)); const actions = useResourceActions(); const [mediaUrl, setMediaUrl] = useState(''); const [previewError, setPreviewError] = useState(''); const [accessibility, setAccessibility] = useState(resource.accessibilityText ?? ''); const [message, setMessage] = useState('');
  const download = async () => { const value = await actions.access(resource.id, 'download'); window.open(value.url, '_blank', 'noopener,noreferrer'); };
  const loadMedia = async () => { try { setMediaUrl((await actions.access(resource.id, 'inline')).url); } catch { setPreviewError('No se pudo iniciar la reproducción. El original sigue disponible.'); } };
  return <article className="mx-auto mt-5 max-w-4xl"><div className="flex items-start gap-3"><ResourceIcon resource={resource} size={36}/><div className="flex-1"><h1 className="text-2xl font-semibold">{resource.title}</h1><p className="text-sm text-outline">{resource.mediaType} · {resource.byteSize == null ? 'Tamaño desconocido' : `${(resource.byteSize / 1024 / 1024).toFixed(1)} MiB`} · {resource.origin} · {resource.status}</p></div><Button variant="primary" onClick={() => void download()}>Descargar original</Button></div>
    <section className="mt-6 rounded-lg border border-border p-4" aria-label="Vista previa">{preview.isPending && <p role="status">Preparando vista previa…</p>}{preview.isError && <p role="alert">No se pudo mostrar la vista previa. Puedes descargar el original.</p>}{preview.data?.url && resource.mediaType?.startsWith('image/') && <img className="max-h-[65vh] max-w-full" src={preview.data.url} alt={resource.accessibilityText || resource.title} onError={() => setPreviewError('La imagen no pudo previsualizarse. El original sigue disponible.')}/>} {preview.data?.url && resource.mediaType === 'application/pdf' && <iframe className="h-[65vh] w-full" src={preview.data.url} title={`Vista previa de ${resource.title}`} onError={() => setPreviewError('El PDF no pudo previsualizarse. El original sigue disponible.')}/>} {media && !mediaUrl && <Button variant="outline" onClick={() => void loadMedia()}>Cargar reproductor</Button>}{mediaUrl && resource.mediaType?.startsWith('audio/') && <audio className="w-full" controls preload="none" src={mediaUrl}>Tu navegador no puede reproducir este audio.</audio>}{mediaUrl && resource.mediaType?.startsWith('video/') && <video className="max-h-[65vh] w-full" controls preload="none" src={mediaUrl}>Tu navegador no puede reproducir este video.</video>}{!previewable && !media && <p>No hay vista previa para este formato. El original está disponible para descarga.</p>}{previewError && <p role="alert" className="mt-2 text-red-600">{previewError}</p>}</section>
    {resource.accessibilityRequired && <section className="mt-6"><label className="block text-sm font-medium">Texto alternativo o descripción accesible{resource.accessibilityMissing && <span className="ml-2 text-red-600">Requerido</span>}<textarea className="mt-1 min-h-28 w-full rounded border border-border bg-background p-2" maxLength={2000} value={accessibility} onChange={event => setAccessibility(event.target.value)}/></label><Button className="mt-2" variant="primary" disabled={actions.accessibility.isPending} onClick={async () => { try { await actions.accessibility.mutateAsync({ id: resource.id, text: accessibility }); setMessage('Información de accesibilidad guardada.'); } catch { setMessage('No se pudo guardar.'); } }}>Guardar accesibilidad</Button>{message && <p role="status" className="mt-2">{message}</p>}</section>}
  </article>;
}

function LinkResource({ resource }: { resource: ResourceDetail }) {
  const actions = useLinkActions(); const [editing, setEditing] = useState(false); const [title, setTitle] = useState(resource.title); const [description, setDescription] = useState(resource.description ?? ''); const [message, setMessage] = useState('');
  const save = async (event: FormEvent) => { event.preventDefault(); try { await actions.update.mutateAsync({ id: resource.id, title, description }); setEditing(false); setMessage('Enlace actualizado.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'No se pudo guardar.'); } };
  return <article className="mx-auto mt-5 max-w-3xl"><div className="flex items-start gap-3"><LinkIcon size={36}/><div className="min-w-0 flex-1"><h1 className="text-2xl font-semibold">{resource.title}</h1><a className="block truncate text-sm text-blue-600 underline" href={resource.url ?? '#'} target="_blank" rel="noopener noreferrer">{resource.url}</a></div><Button variant="outline" onClick={() => setEditing(value => !value)}>Editar</Button></div>{resource.previewImageUrl && <img className="mt-5 max-h-72 rounded border border-border" src={resource.previewImageUrl} alt=""/>}<p className="mt-4">{resource.description || 'Sin descripción.'}</p>{resource.metadataStatus === 'pending' && <p role="status" className="mt-3 text-sm text-outline">Obteniendo metadatos…</p>}{resource.metadataStatus === 'failed' && <div role="alert" className="mt-3"><p>No se pudieron obtener los metadatos. El enlace sigue guardado.</p><Button className="mt-2" variant="outline" disabled={actions.retry.isPending} onClick={async () => { try { await actions.retry.mutateAsync({ id: resource.id }); setMessage('Reintento iniciado.'); } catch { setMessage('No se pudo reintentar.'); } }}>Reintentar metadatos</Button></div>}{editing && <form className="mt-6 rounded border border-border p-4" onSubmit={save}><label className="block text-sm font-medium">Título<input className="mt-1 w-full rounded border border-border bg-background p-2" maxLength={160} value={title} onChange={event => setTitle(event.target.value)}/></label><label className="mt-4 block text-sm font-medium">Descripción<textarea className="mt-1 min-h-28 w-full rounded border border-border bg-background p-2" maxLength={1000} value={description} onChange={event => setDescription(event.target.value)}/></label><Button className="mt-3" type="submit" variant="primary" disabled={actions.update.isPending}>Guardar cambios</Button></form>}{message && <p role="status" className="mt-3">{message}</p>}</article>;
}

function LinkEditor({ busy, onCancel, onSave }: { busy: boolean; onCancel: () => void; onSave: (url: string) => Promise<void> }) {
  const [url, setUrl] = useState(''); const [message, setMessage] = useState('');
  const submit = async (event: FormEvent) => { event.preventDefault(); try { const parsed = new URL(url); if (!['http:', 'https:'].includes(parsed.protocol)) throw new Error(); await onSave(url); } catch (error) { setMessage(error instanceof Error && error.message ? error.message : 'Ingresa una URL HTTP o HTTPS válida.'); } };
  return <form className="mx-auto mt-16 max-w-xl" onSubmit={submit}><h2 className="text-xl font-semibold">Guardar enlace web</h2><label className="mt-5 block text-sm font-medium">Dirección web<input className="mt-1 w-full rounded border border-border bg-background p-2" type="url" placeholder="https://ejemplo.com" required value={url} onChange={event => setUrl(event.target.value)}/></label>{message && <p role="alert" className="mt-3 text-red-600">{message}</p>}<div className="mt-5 flex gap-2"><Button type="button" onClick={onCancel}>Cancelar</Button><Button type="submit" variant="primary" disabled={busy}>{busy ? 'Guardando…' : 'Guardar enlace'}</Button></div></form>;
}

function NoteEditor({ note, busy, onCancel, onSave }: { note?: Note; busy: boolean; onCancel: () => void; onSave: (input: NoteInput) => Promise<boolean | undefined> }) {
  const [title, setTitle] = useState(note?.title ?? ''); const [description, setDescription] = useState(note?.description ?? ''); const [content, setContent] = useState(note?.currentVersion.content ?? ''); const [message, setMessage] = useState('');
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!title.trim()) { setMessage('El título es obligatorio.'); return; } try { const unchanged = await onSave({ title, description, content }); setMessage(unchanged ? 'El contenido ya estaba actualizado.' : 'Nota guardada.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'No se pudo guardar. Puedes reintentar.'); } };
  return <form className="mx-auto mt-4 max-w-3xl" onSubmit={submit}><label className="block text-sm font-medium">Título<input className="mt-1 w-full rounded border border-border bg-background p-2 text-xl" value={title} maxLength={160} onChange={event => setTitle(event.target.value)}/></label><label className="mt-4 block text-sm font-medium">Descripción<input className="mt-1 w-full rounded border border-border bg-background p-2" value={description} onChange={event => setDescription(event.target.value)}/></label><label className="mt-4 block text-sm font-medium">Contenido<textarea className="mt-1 min-h-80 w-full rounded border border-border bg-background p-3" value={content} onChange={event => setContent(event.target.value)}/></label>{message && <p role="status" className="mt-3 text-sm">{message}</p>}<div className="mt-5 flex gap-2"><Button type="button" onClick={onCancel}>Cancelar</Button><Button type="submit" variant="primary" disabled={busy}>{busy ? 'Guardando…' : 'Guardar'}</Button></div></form>;
}
