import { useState } from 'react';
import type { FormEvent } from 'react';
import { File as FileIcon, FileText, Image as ImageIcon, Music, Video } from 'lucide-react';
import { useLocation, useNavigate } from 'react-router-dom';
import { UploadTray } from '../components/uploads/UploadTray';
import { Button } from '../components/ui/Button';
import { Card } from '../components/ui/Card';
import { ViewToolbar } from '../components/ui/ViewToolbar';
import { type Note, type NoteInput, useNoteActions } from '../data/useNotes';
import { type ResourceDetail, type ResourceSummary, useResource, useResourceAccess, useResourceActions, useResources } from '../data/useResources';

export function Library() {
  const [viewMode, setViewMode] = useState<'grid' | 'list'>('list'); const [creating, setCreating] = useState(false); const navigate = useNavigate(); const location = useLocation(); const resourceId = location.pathname.match(/^\/library\/([^/]+)$/)?.[1];
  const resources = useResources(); const detail = useResource(resourceId); const noteActions = useNoteActions(); const items = resources.data?.pages.flatMap(page => page.data) ?? [];
  if (resourceId) { const selected = detail.data; return <main className="w-full px-6 md:px-8 py-6"><Button onClick={() => navigate('/library')}>← Biblioteca</Button>{detail.isPending && <p role="status" className="mt-5">Cargando recurso…</p>}{detail.isError && <p role="alert" className="mt-5 text-red-600">No se pudo abrir el recurso.</p>}{selected?.type === 'note' && <NoteEditor note={{ ...selected, currentVersion: { id: '', ordinal: 1, content: selected.content ?? '' } }} busy={noteActions.update.isPending} onCancel={() => navigate('/library')} onSave={async body => { const saved = await noteActions.update.mutateAsync({ id: selected.id, body }); return saved.contentUnchanged; }}/>} {selected?.type === 'file' && <FileResource resource={selected}/>}</main>; }
  return <main className="w-full px-6 md:px-8 py-6 pb-32" aria-labelledby="library-title">
    <div className="flex items-center justify-between"><div><h1 id="library-title" className="text-xl font-semibold">Biblioteca</h1><p className="text-sm text-outline">Recursos reutilizables en distintos proyectos y diagramas.</p></div><ViewToolbar viewMode={viewMode} setViewMode={setViewMode} onNew={() => setCreating(true)}/></div>
    <UploadTray/>
    {resources.isPending && <p role="status" className="mt-6">Cargando Biblioteca…</p>}
    {resources.isError && <div role="alert" className="mt-6"><p className="text-red-600">No se pudo cargar la Biblioteca.</p><Button variant="outline" onClick={() => resources.refetch()}>Reintentar</Button></div>}
    {!resources.isPending && !resources.isError && items.length === 0 && <section className="mt-8 rounded-lg border border-dashed border-border p-10 text-center"><FileText className="mx-auto text-outline" size={36}/><h2 className="mt-3 font-medium">Tu Biblioteca está vacía</h2><p className="mt-1 text-sm text-outline">Crea una nota o carga un archivo para reutilizarlo después.</p><Button className="mt-4" variant="primary" onClick={() => setCreating(true)}>Crear una nota</Button></section>}
    {items.length > 0 && (viewMode === 'grid' ? <div className="mt-6 grid grid-cols-1 sm:grid-cols-3 md:grid-cols-4 gap-4">{items.map(resource => <Card key={resource.id} title={resource.title} subtitle={resource.description || resource.mediaType || 'Nota'} icon={<ResourceIcon resource={resource} size={32}/>} onClick={() => navigate(`/library/${resource.id}`)}/>)}</div> : <div className="mt-6 divide-y divide-border border-y border-border">{items.map(resource => <button key={resource.id} className="flex w-full items-center gap-3 py-3 text-left hover:bg-surface-variant focus-visible:outline-2" onClick={() => navigate(`/library/${resource.id}`)}><ResourceIcon resource={resource} size={18}/><span className="flex-1"><strong className="block font-medium">{resource.title}</strong><small className="text-outline">{resource.description || resource.mediaType || 'Nota'} · {resource.status}</small></span><time className="text-xs text-outline">{new Date(resource.updatedAt).toLocaleDateString()}</time></button>)}</div>)}
    {resources.hasNextPage && <Button className="mt-5" variant="outline" onClick={() => resources.fetchNextPage()}>Cargar más</Button>}
    {creating && <div className="fixed inset-0 z-50 overflow-auto bg-background p-6"><NoteEditor busy={noteActions.create.isPending} onCancel={() => setCreating(false)} onSave={async body => { const saved = await noteActions.create.mutateAsync(body); setCreating(false); navigate(`/library/${saved.id}`); return false; }}/></div>}
  </main>;
}

function ResourceIcon({ resource, size }: { resource: ResourceSummary; size: number }) { if (resource.type === 'note') return <FileText size={size}/>; if (resource.mediaType?.startsWith('image/')) return <ImageIcon size={size}/>; if (resource.mediaType?.startsWith('audio/')) return <Music size={size}/>; if (resource.mediaType?.startsWith('video/')) return <Video size={size}/>; return <FileIcon size={size}/>; }

function FileResource({ resource }: { resource: ResourceDetail }) {
  const previewable = resource.mediaType === 'application/pdf' || resource.mediaType?.startsWith('image/'); const media = resource.mediaType?.startsWith('audio/') || resource.mediaType?.startsWith('video/'); const preview = useResourceAccess(resource.id, Boolean(previewable)); const actions = useResourceActions(); const [mediaUrl, setMediaUrl] = useState(''); const [previewError, setPreviewError] = useState(''); const [accessibility, setAccessibility] = useState(resource.accessibilityText ?? ''); const [message, setMessage] = useState('');
  const download = async () => { const value = await actions.access(resource.id, 'download'); window.open(value.url, '_blank', 'noopener,noreferrer'); };
  const loadMedia = async () => { try { setMediaUrl((await actions.access(resource.id, 'inline')).url); } catch { setPreviewError('No se pudo iniciar la reproducción. El original sigue disponible.'); } };
  return <article className="mx-auto mt-5 max-w-4xl"><div className="flex items-start gap-3"><ResourceIcon resource={resource} size={36}/><div className="flex-1"><h1 className="text-2xl font-semibold">{resource.title}</h1><p className="text-sm text-outline">{resource.mediaType} · {resource.byteSize == null ? 'Tamaño desconocido' : `${(resource.byteSize / 1024 / 1024).toFixed(1)} MiB`} · {resource.origin} · {resource.status}</p></div><Button variant="primary" onClick={() => void download()}>Descargar original</Button></div>
    <section className="mt-6 rounded-lg border border-border p-4" aria-label="Vista previa">{preview.isPending && <p role="status">Preparando vista previa…</p>}{preview.isError && <p role="alert">No se pudo mostrar la vista previa. Puedes descargar el original.</p>}{preview.data?.url && resource.mediaType?.startsWith('image/') && <img className="max-h-[65vh] max-w-full" src={preview.data.url} alt={resource.accessibilityText || resource.title} onError={() => setPreviewError('La imagen no pudo previsualizarse. El original sigue disponible.')}/>} {preview.data?.url && resource.mediaType === 'application/pdf' && <iframe className="h-[65vh] w-full" src={preview.data.url} title={`Vista previa de ${resource.title}`} onError={() => setPreviewError('El PDF no pudo previsualizarse. El original sigue disponible.')}/>} {media && !mediaUrl && <Button variant="outline" onClick={() => void loadMedia()}>Cargar reproductor</Button>}{mediaUrl && resource.mediaType?.startsWith('audio/') && <audio className="w-full" controls preload="none" src={mediaUrl}>Tu navegador no puede reproducir este audio.</audio>}{mediaUrl && resource.mediaType?.startsWith('video/') && <video className="max-h-[65vh] w-full" controls preload="none" src={mediaUrl}>Tu navegador no puede reproducir este video.</video>}{!previewable && !media && <p>No hay vista previa para este formato. El original está disponible para descarga.</p>}{previewError && <p role="alert" className="mt-2 text-red-600">{previewError}</p>}</section>
    {resource.accessibilityRequired && <section className="mt-6"><label className="block text-sm font-medium">Texto alternativo o descripción accesible{resource.accessibilityMissing && <span className="ml-2 text-red-600">Requerido</span>}<textarea className="mt-1 min-h-28 w-full rounded border border-border bg-background p-2" maxLength={2000} value={accessibility} onChange={event => setAccessibility(event.target.value)}/></label><Button className="mt-2" variant="primary" disabled={actions.accessibility.isPending} onClick={async () => { try { await actions.accessibility.mutateAsync({ id: resource.id, text: accessibility }); setMessage('Información de accesibilidad guardada.'); } catch { setMessage('No se pudo guardar.'); } }}>Guardar accesibilidad</Button>{message && <p role="status" className="mt-2">{message}</p>}</section>}
  </article>;
}

function NoteEditor({ note, busy, onCancel, onSave }: { note?: Note; busy: boolean; onCancel: () => void; onSave: (input: NoteInput) => Promise<boolean | undefined> }) {
  const [title, setTitle] = useState(note?.title ?? ''); const [description, setDescription] = useState(note?.description ?? ''); const [content, setContent] = useState(note?.currentVersion.content ?? ''); const [message, setMessage] = useState('');
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!title.trim()) { setMessage('El título es obligatorio.'); return; } try { const unchanged = await onSave({ title, description, content }); setMessage(unchanged ? 'El contenido ya estaba actualizado.' : 'Nota guardada.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'No se pudo guardar. Puedes reintentar.'); } };
  return <form className="mx-auto mt-4 max-w-3xl" onSubmit={submit}><label className="block text-sm font-medium">Título<input className="mt-1 w-full rounded border border-border bg-background p-2 text-xl" value={title} maxLength={160} onChange={event => setTitle(event.target.value)}/></label><label className="mt-4 block text-sm font-medium">Descripción<input className="mt-1 w-full rounded border border-border bg-background p-2" value={description} onChange={event => setDescription(event.target.value)}/></label><label className="mt-4 block text-sm font-medium">Contenido<textarea className="mt-1 min-h-80 w-full rounded border border-border bg-background p-3" value={content} onChange={event => setContent(event.target.value)}/></label>{message && <p role="status" className="mt-3 text-sm">{message}</p>}<div className="mt-5 flex gap-2"><Button type="button" onClick={onCancel}>Cancelar</Button><Button type="submit" variant="primary" disabled={busy}>{busy ? 'Guardando…' : 'Guardar'}</Button></div></form>;
}
